services:
  db:
    image: leogloriainfnet/postgres-tp2-spring:1.0
    container_name: tp2-springboot
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: adm
    ports:
      - "5432:5432"
