spring:
  application:
    name: spring-boot-services
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: adm
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  main:
    allow-bean-definition-overriding: true
  spring:
    elasticsearch:
      uris: http://localhost:9200